//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supermarket_salem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managerr
    {
        public int M_ID { get; set; }
        public string M_Name { get; set; }
    }
}
