//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supermarket_salem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int S_ID { get; set; }
        public string S_Name { get; set; }
        public Nullable<int> S_Age { get; set; }
        public string Class { get; set; }
        public Nullable<int> T_ID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
